Web_1D2C/Web_1D2C/Controllers/ShoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_1D2C.Models;
using PagedList;
using PagedList.Mvc;

namespace Web_1D2C.Controllers
{
    public class ShoesController : Controller
    {
        // GET: Shoes
        dbQLBangiayDataContext data = new dbQLBangiayDataContext();

        

        private List<SANPHAM> Layspmoi(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var spmoi = Layspmoi(8);
            return View(spmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Nhasanxuat()
        {
            var nhasanxuat = from nsx in data.NHASAXUATs select nsx;
            return PartialView(nhasanxuat);
        }
       
        public ActionResult Loai(int ID)
        {
            var loai = from l in data.LOAIs where l.MaNSX==ID select l;
            return PartialView(loai);
        }
        public ActionResult SPtheoLoai(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.MaLoai == id select sp;
            return View(sanpham);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.Masp == id select sp;
            return View(sanpham.Single());
        }
        [HttpGet]
        public ActionResult SPlienquan(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.MaLoai == id select sp;
            return PartialView(sanpham);
        }
    }
}

Web_1D2C/Web_1D2C/Views/Shoes/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutInfoShoes.cshtml";
}

<div class="wrapper row">
    <div class="preview col-md-6">
        <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1"><img src="~/Images/@Model.Anhbia" alt=""></div>
            <div class="tab-pane" id="pic-2"><img src="~/Images/@Model.Anhbia" alt""=></div>
            <div class="tab-pane" id="pic-3"><img src="~/Images/@Model.Anhbia" alt""=></div>
            <div class="tab-pane" id="pic-4"><img src="~/Images/@Model.Anhbia" alt""=></div>
        </div>

        <ul class="preview-thumbnail nav nav-tabs">
            <div class="logo__small-img"></div>
            <div class="menu-img"><span></span></div>
            <li class="active">

                <a data-target="#pic-1" data-toggle="tab"><img src="~/Images/@Model.Anhbia" alt""=></a>
            </li>
            <li>
                <a data-target="#pic-2" data-toggle="tab"><img src="~/Images/@Model.Anhbia" alt""=></a>
            </li>
            <li>
                <a data-target="#pic-3" data-toggle="tab"><img src="~/Images/@Model.Anhbia" alt""=></a>
            </li>
            <li>
                <a data-target="#pic-4" data-toggle="tab"><img src="~/Images/@Model.Anhbia" alt""=></a>
            </li>
        </ul>
    </div>

    <div class="details col-md-3">

        <h3 class="product-title">@Model.Tensp</h3>

        <div class="rating">

            <div class="stars">
                <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span>
            </div> <span class="review-no">123 đánh giá</span>
        </div>

        <h4 class="price">Giá bán: @String.Format("{0:0,0}", Model.Giaban) VND</h4>

        <p class="vote">
            <strong>91%</strong> người mua hài lòng với sản phẩm này <strong>(87 bình chọn)</strong>
        </p>

        <h5 class="sizes">
            Kích cỡ:
            <span class="size" data-toggle="tooltip" title="small">36</span>
            <span class="size" data-toggle="tooltip" title="medium">37</span>
            <span class="size" data-toggle="tooltip" title="large">38</span>
            <span class="size" data-toggle="tooltip" title="xtra large">39</span>
            <span class="size" data-toggle="tooltip" title="big-1">40</span>
            <span class="size" data-toggle="tooltip" title="big-2">41</span>
            <span class="size" data-toggle="tooltip" title="big-3">42</span>
            <span class="size" data-toggle="tooltip" title="big-4">43</span>
        </h5>

        <div class="action">

            <a href="@Url.Action("ThemGiohang","GioHang",new { @iMasp= @Model.Masp, @strURL=Request.Url.ToString() })" class="btn btn-info" role="button" style="background-color:orange" border="none">Thêm vào giỏ</a>
            <a href="#" target="_blank"><button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button> </a>
            <div style="padding-top:15px">
                <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&width=450&layout=standard&action=like&size=small&show_faces=true&share=true&height=80&appId" width="450" height="80" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

            </div>
        </div>

    </div>

</div>
<div class="container-fluid" style="padding-top:20px; margin: 0 auto; width: 80%">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.2"></script>
    <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>
</div>

Web_1D2C/Web_1D2C/Views/Shoes/Index.cshtml
@model IEnumerable<Web_1D2C.Models.SANPHAM>
@*@using Web_1D2C.Models
    @using PagedList.Mvc;
    @model PagedList.PagedList<SANPHAM>*@


@{

    ViewBag.Title = "Index";
    
    Layout = "~/Views/Shared/_LayoutUser1.cshtml";

}

<div class="row">
    <div class="col-12">
        <h1 class="section-title">Sản Phẩm Mới</h1>
    </div>
</div>
<div class="movie__content">
    <div class="owl-carousel">
        @foreach (var sp in Model)
        {

            @*<div class="col-sm-6 col-md-3 text-center">

                    <a href="@Url.Action("Details","Shoes", new {id = sp.Masp })">
                        <div class="shoes__item">
                            <img src="~/Images/@sp.Anhbia" class="img-fluid w-100" style="height:300px">
                            <div class="shoes__overlay"></div>
                            <div class="shoes__detail w-100 text-center text-white">
                                <i class="fa fa-play d-block mx-auto mb-3 video-play venobox vbox-item" href="https://youtu.be/aOXvyd9v1cg" data-vbtype="video"></i>
                                <a class="d-block text-white mb-2" >READ MORE</a>
                                <span>@sp.NHASAXUAT.TenNSX</span>
                            </div>
                        </div>

                        <span>
                            <p class="shoes__name text-center my-3">@sp.Tensp</p>
                        </span>
                    </a>
                    <i class="fa fa-star shoes__star"></i>
                    <i class="fa fa-star shoes__star"></i>
                    <i class="fa fa-star shoes__star"></i>
                    <i class="fa fa-star shoes__star"></i>
                    <i class="fa fa-star shoes__star"></i>
                </div>*@

        <div class="movie__item item">
            <a style="text-decoration:none" href="@Url.Action("Details","Shoes", new {id = sp.Masp })">
                <img src="~/Images/@sp.Anhbia" class="img-fluid w-100" style="height:200px">

                <p>@sp.Tensp</p>
                
                    <button class="btn-read-more">Xem Thêm</button> 
            </a>
        </div>


}
        @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
            <div class="MenuTrang">

                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
            </div>
            <style>
                .MenuTrang li {
                    display: inline;
                }
            </style>*@
        </div>
        </div>

Web_1D2C/Web_1D2C/Views/Shoes/Loai.cshtml
@model IEnumerable<Web_1D2C.Models.LOAI>

@foreach (var item in Model)
{
    <a class="dropdown-item" href="@Url.Action("SPTheoloai","Shoes",new {id =item.MaLoai})">@item.TenLoai</a>
    <div class="dropdown-divider"></div>

}

Web_1D2C/Web_1D2C/Views/Shoes/Nhasanxuat.cshtml
@model IEnumerable<Web_1D2C.Models.NHASAXUAT>

@foreach (var item in Model)
{
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="@Url.Action("SPTheoNSX","Shoes",new {id =item.MaNSX})" role="button" aria-haspopup="true" aria-expanded="false">
            @item.TenNSX
        </a>
        <div class="dropdown-menu">
            @Html.Action("Loai", "Shoes", new { id = item.MaNSX })
        </div>
    </li>
}
   

Web_1D2C/Web_1D2C/Views/Shoes/SPlienquan.cshtml
@model IEnumerable<Web_1D2C.Models.SANPHAM>

@foreach (var item in Model)
{
    <div class="col-sm-6 col-md-3 text-center">
        <div class="shoes__item">

            <div class="shoes__overlay"></div>
            <div class="shoes__detail w-100 text-center text-white">
                <i class="fa fa-play d-block mx-auto mb-3 video-play venobox vbox-item" href="https://youtu.be/aOXvyd9v1cg" data-vbtype="video"></i>
                <a class="d-block text-white mb-2">READ MORE</a>
                <span>Released: 7 Mar, 2017</span>
            </div>
        </div>
        <a href="@Url.Action("Details","Shoes",new {id = item.Masp})">
            <img alt="" src="~/Images/@item.Anhbia" class="img-fluid w-100">
            <span>
                <p class="shoes__name text-center my-3">@item.Tensp</p>
            </span>
        </a>
        <i class="fa fa-star shoes__star"></i>
        <i class="fa fa-star shoes__star"></i>
        <i class="fa fa-star shoes__star"></i>
        <i class="fa fa-star shoes__star"></i>
        <i class="fa fa-star shoes__star"></i>
    </div>

}

Web_1D2C/Web_1D2C/Views/Shoes/SPtheoLoai.cshtml
@{
    ViewBag.Title = "SPtheoLoai";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="row">
    <div class="col-12">
        <h1 class="section-title">SẢN PHẨM</h1>
    </div>
</div>
<div class="row">
    @foreach (var sp in Model)
    {

        <div class="col-sm-6 col-md-3 text-center">
            
            <a href="@Url.Action("Details","Shoes", new {id = sp.Masp })">
                <div class="shoes__item">
                    <img alt="" src="~/Images/@sp.Anhbia" class="img-fluid w-100" style="height:300px">
                    <div class="shoes__overlay"></div>
                    <div class="shoes__detail w-100 text-center text-white">
                        <i class="fa fa-play d-block mx-auto mb-3 video-play venobox vbox-item" href="https://youtu.be/aOXvyd9v1cg" data-vbtype="video"></i>
                        <a class="d-block text-white mb-2">READ MORE</a>
                        <span>@sp.NHASAXUAT.TenNSX</span>
                    </div>
                </div>
                
                <span>
                    <p class="shoes__name text-center my-3">@sp.Tensp</p>
                </span>
            </a>
            <i class="fa fa-star shoes__star"></i>
            <i class="fa fa-star shoes__star"></i>
            <i class="fa fa-star shoes__star"></i>
            <i class="fa fa-star shoes__star"></i>
            <i class="fa fa-star shoes__star"></i>
        </div>
    }
</div>