Web_1D2C/Web_1D2C/Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_1D2C.Models;

namespace Web_1D2C.Controllers
{
    public class NguoidungController : Controller
    {
        // GET: Nguoidung
        dbQLBangiayDataContext data = new dbQLBangiayDataContext();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            // Gán các giá tị người dùng nhập liệu cho các biến 
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu";
            }


            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Email không được bỏ trống";
            }

            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi6"] = "Phải nhập điện thoai";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)

                kh.HoTen = hoten;
                kh.Taikhoan = tendn;
                kh.Matkhau = matkhau;
                kh.Email = email;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.Ngaysinh = DateTime.Parse(ngaysinh);
                data.KHACHHANGs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            // Gán các giá trị người dùng nhập liệu cho các biến 
            var tendn = collection["TenDN"];
            var matkhau =collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (kh)

                KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == matkhau);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["Taikhoan"] = kh;
                    return RedirectToAction("Index", "Shoes");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return View();
        }
    }
}

Web_1D2C/Web_1D2C/Controllers/ShoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_1D2C.Models;
using PagedList;
using PagedList.Mvc;

namespace Web_1D2C.Controllers
{
    public class ShoesController : Controller
    {
        // GET: Shoes
        dbQLBangiayDataContext data = new dbQLBangiayDataContext();

        

        private List<SANPHAM> Layspmoi(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var spmoi = Layspmoi(8);
            return View(spmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Nhasanxuat()
        {
            var nhasanxuat = from nsx in data.NHASAXUATs select nsx;
            return PartialView(nhasanxuat);
        }
       
        public ActionResult Loai(int ID)
        {
            var loai = from l in data.LOAIs where l.MaNSX==ID select l;
            return PartialView(loai);
        }
        public ActionResult SPtheoLoai(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.MaLoai == id select sp;
            return View(sanpham);
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.Masp == id select sp;
            return View(sanpham.Single());
        }
        [HttpGet]
        public ActionResult SPlienquan(int id)
        {
            var sanpham = from sp in data.SANPHAMs where sp.MaLoai == id select sp;
            return PartialView(sanpham);
        }
    }
}

Web_1D2C/Web_1D2C/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web_1D2C/Web_1D2C/Views/Shared/_LayoutCart.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>1 Đôi 2 Chiếc</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="png" href="/USER/ASSETS/Images/logo.png" />
    <!-- CSS -->



    <link href="~/Content/index.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/venobox.css" rel="stylesheet" />
    <link href="~/Content/infoShoes.css" rel="stylesheet" />
    <!-- Glyphycons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- GG Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">

</head>

<body>
    <!-- HEADER -->
    <header class="container-fluid">
        <div class="row">
            <div class="header__left col-2">
                <div class="header__logo">
                    <a href="@Url.Action("Index","Shoes")"><img class="logo" src="~/Images/logo.png" alt="Logo nè"></a>
                </div>
            </div>
            <div class="header__right col-10">
                <div class="header__top">
                    <ul class="header-menu header-menu-top">
                        <li>
                            <a href="#">Trợ Giúp</a>
                        </li>
                  
                        <li>
                            <a href="loginAdmin.html"><i class="fa fa-user-circle"></i>Đăng nhập</a>
                        </li>
                    </ul>
                </div>
                <div class="header__bottom">
                    <ul class="header-menu header-menu-bot nav nav-tabs">
                        @Html.Action("Nhasanxuat", "Shoes")
                        <form class="header-menu header-menu-bot" style="float: right">
                            <input type="search" name="" id="search" placeholder="Tìm sản phẩm">

                        </form>
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <!-- END HEADER -->
    <div>
        @RenderBody()
    </div>
    <!-- CONTACT -->
    <section class="contact">
        <div class="contact__info">
            <div class="contact__info__item">
                <i class="fa fa-home"></i>
                <p>103 Nguyễn Cư Trinh</p>
                <p>Quận 1 - TP.HCM</p>
            </div>

            <div class="contact__info__item">
                <i class="fa fa-phone"></i>
                <p>+(84) 888 734 797</p>
                <p>+(84) 123 456 535</p>
            </div>
        </div>
        <div class="contact__map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1589.56504099228!2d106.689351495618!3d10.763420041576216!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f1738aa5e2f%3A0x772e8509214d82aa!2zMTAzIE5ndXnhu4VuIEPGsCBUcmluaCwgUGjGsOG7nW5nIE5ndXnhu4VuIEPGsCBUcmluaCwgUXXhuq1uIDEsIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1540633891245"
                    frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </section>
    <!-- END CONTACT -->
    <!--FOOTER-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <h3>LIÊN HỆ</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Câu hỏi thường gặp</a></li>
                        <li><a href="#">Gửi lại cho tôi phản hồi</a></li>
                        <li><a href="#">Liên hệ chúng tôi</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>GIỚI THIỆU GIÀY MỚI</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Về chúng tôi</a></li>
                        <li><a href="#">Tìm chúng tôi</a></li>
                        <li><a href="#">Tin tức</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>THỦ TỤC PHÁP LÍ</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Điều khoản và điều kiện</a></li>
                        <li><a href="#">Gửi lại cho tôi phản hồi</a></li>
                        <li><a href="#">Chính sách cookie</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>KẾT NỐI VỚI CHÚNG TÔI</h3>
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/profile.php?id=100013828747923"> <i class="fa fa-facebook mr-2"></i> Facebook</a>
                        </li>
                        <li><a href="#"><i class="fa fa-instagram"></i> Instagram</a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i> Gmail</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12 ">
                    <p class="border-top copy-right text-white pt-3 mt-5">
                        2019 © Đời Chỉ Thế Thôi / Web design by 1 Đôi 2 Chiếc
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

Web_1D2C/Web_1D2C/Views/Shared/_LayoutInfoShoes.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>1 Đôi 2 Chiếc</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="png" href="~/Images/logo.png" />
    <!-- CSS -->



    <link href="~/Content/index.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/venobox.css" rel="stylesheet" />
    <link href="~/Content/infoShoes.css" rel="stylesheet" />
    <!-- Glyphycons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">*@
    <!-- GG Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">

    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


</head>

<body>
    <!-- HEADER -->
    <header class="container-fluid">
        <div class="row">
            <div class="header__left col-2">
                <div class="header__logo">
                    <a href="@Url.Action("Index","Shoes")"><img class="logo" src="~/Images/logo.png" alt="Logo nè"></a>
                </div>
            </div>
            <div class="header__right col-10">
                <div class="header__top">
                    <ul class="header-menu header-menu-top">
                        <li>
                            <a href="#">HELP</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Dangnhap","Nguoidung")"><i class="fa fa-user-circle"></i>LOGIN </a>
                        </li>
                    </ul>
                </div>
                <br />


                <div class="header__bottom clearfix header__nav">

                    <ul class="header-menu header-menu-bot nav nav-tabs">
                        @Html.Action("Nhasanxuat", "Shoes")
                    </ul>
                    <form class="header-menu header-menu-bot " style="float: right">
                        <input type="search" name="" id="search" placeholder="Tìm sản phẩm">
                        @Html.Action("GiohangPartial", "Giohang")
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- END HEADER -->

    <div class="container">
        <div class="row">
            <div class="@*col-9*@">
                <div>
                    @RenderBody()
                </div>

            </div>
        </div>
        <div class="col-md-9"> </div>
    </div>



    <!--SHOWING SHOES-->
    <section class="shoes">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="section-title">SẢN PHẨM LIÊN QUAN</h1>
                    @Html.Action("SPlienquan", "Shoes")
                </div>
            </div>
            <div class="row">

            </div>
        </div>
    </section>
    <!-- END SHOWING SHOES -->
    <!-- CONTACT -->
    <section class="contact">
        <div class="contact__info">
            <div class="contact__info__item">
                <i class="fa fa-home"></i>
                <p>103 Nguyễn Cư Trinh</p>
                <p>Quận 1 - TP.HCM</p>
            </div>

            <div class="contact__info__item">
                <i class="fa fa-phone"></i>
                <p>+(84) 888 734 797</p>
                <p>+(84) 123 456 535</p>
            </div>
        </div>
        <div class="contact__map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1589.56504099228!2d106.689351495618!3d10.763420041576216!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f1738aa5e2f%3A0x772e8509214d82aa!2zMTAzIE5ndXnhu4VuIEPGsCBUcmluaCwgUGjGsOG7nW5nIE5ndXnhu4VuIEPGsCBUcmluaCwgUXXhuq1uIDEsIEjhu5MgQ2jDrSBNaW5oLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1540633891245"
                    frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </section>
    <!-- END CONTACT -->
    <!--FOOTER-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <h3>LIÊN HỆ</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Câu hỏi thường gặp</a></li>
                        <li><a href="#">Gửi lại cho tôi phản hồi</a></li>
                        <li><a href="#">Liên hệ chúng tôi</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>GIỚI THIỆU GIÀY MỚI</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Về chúng tôi</a></li>
                        <li><a href="#">Tìm chúng tôi</a></li>
                        <li><a href="#">Tin tức</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>THỦ TỤC PHÁP LÍ</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Điều khoản và điều kiện</a></li>
                        <li><a href="#">Gửi lại cho tôi phản hồi</a></li>
                        <li><a href="#">Chính sách cookie</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h3>KẾT NỐI VỚI CHÚNG TÔI</h3>
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/profile.php?id=100013828747923"> <i class="fa fa-facebook mr-2"></i> Facebook</a>
                        </li>
                        <li><a href="#"><i class="fa fa-instagram"></i> Instagram</a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i> Gmail</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12 ">
                    <p class="border-top copy-right text-white pt-3 mt-5">
                        2019 © Đời Chỉ Thế Thôi / Web design by 1 Đôi 2 Chiếc
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    @*<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>*@
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>

</html>

Web_1D2C/Web_1D2C/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="png" href="~/Images/logo.png" />
    <title>ADMIN</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    
    <link href="~/Content/admin-2.css" rel="stylesheet" />
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    
                                    <div>
                                        @RenderBody()
                                    </div>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="/ADMIN/APPS/Views/forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("Dangky","Nguoidung")">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
   
    <script src="~/Scripts/jquery.min.js"></script>

    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->

    <script src="~/Scripts/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->

    <script src="~/Scripts/admin-2.js"></script>
</body>
</html>

Web_1D2C/Web_1D2C/Views/Shared/_LayoutĐangki.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="png" href="~/Images/logo.png" />
    <title>ADMIN</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
   
    <link href="~/Content/admin-2.css" rel="stylesheet" />
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Đăng ký tài khoản!</h1>
                            </div>
                            <div>
                                @RenderBody()
                            </div>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Quên mật khẩu?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="@Url.Action("Dangnhap","Nguoidung")">Bạn đã có tài khoản? Đăng nhập!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
   

    <script src="~/Scripts/jquery.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/admin-2.js"></script>
</body>
</html>